apiVersion: v1
kind: Pod
metadata:
  name: postgresql-client
spec:
  containers:
    - name: postgresql-client
      image: postgres:latest  # Prebuilt PostgreSQL client image from Docker Hub
      command: [ "sleep", "infinity" ]  # Keeps the container running so you can exec into it later
