apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_USERNAME: "RmFpc2FsIEtoYW4="  # Base64 encoded
  MYSQL_PASSWORD: "RmFpc2Fsa2hhbjM1QA=="  # Base64 encoded
