apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
spec:
  clusterIP: None  # Makes it a headless service
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
