apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30090
  selector:
    app: prometheus
  type: NodePort
