nano splunk-rbac.yaml
kubectl apply -f splunk-rbac.yaml



apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-sa
  namespace: splunk
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
    
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-rolebinding
subjects:
  - kind: ServiceAccount
    name: fluent-bit-sa
    namespace: splunk
roleRef:
  kind: ClusterRole
  name: fluent-bit-role
  apiGroup: rbac.authorization.k8s.io
