apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-configmap
data:
  MYSQL_DATABASE: "faisal-mysql-db"
  MYSQL_HOST: faisal-mysql-db.clis8ywwg5wd.eu-north-1.rds.amazonaws.com     # Replace with your RDS MYSQL Endpoint
  MYSQL_PORT: "3306"

  ORACLE_DATABASE: "faisal-oracle-db"
  ORACLE_HOST: faisal-oracle-db.clis8ywwg5wd.eu-north-1.rds.amazonaws.com     # Replace with your RDS Oracle Endpoint
  ORACLE_PORT: "1521"

  POSTGRESQL_DATABASE: "faisal-postgresql-db"
  POSTGRESQL_HOST: faisal-postgresql-db.clis8ywwg5wd.eu-north-1.rds.amazonaws.com     # Replace with your RDS PostgreSQL Endpoint
  POSTGRESQL_PORT: "5432"
